In [1]:
import numpy as np

In [2]:
A = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        A[i, j] = (i + 1) ** (4 - j)
detA = np.linalg.det(A)
B = A.copy()
print(B)

[[  1.   1.   1.   1.   1.]
 [ 16.   8.   4.   2.   1.]
 [ 81.  27.   9.   3.   1.]
 [256.  64.  16.   4.   1.]
 [625. 125.  25.   5.   1.]]


In [3]:
b = np.array([0, 0, 0, 1, 1])

for index, number in enumerate(b):
    B[index, 2] = number

detA_3 = np.linalg.det(B)
x_3 = detA_3 / detA

In [4]:
print(detA_3)
print(x_3)

-1548.0000000000018
-5.375000000000072
