Oppgave 1

In [48]:
import numpy as np

a)

In [49]:
# Gauss kalkulator
# Definerer funksjonene for de 3 elementære radoperasjonene.
# Du må selv velge hvilke operasjoner som skal brukes

def adder_rad(A,k,i,j):
    "Adderer k ganger rad j til rad i."
    n = A.shape[0]      # n=antall rader i A
    E = np.eye(n)       # Lager en (n x n)-identitetsmatrise
    if i == j:
        E[i,i] = k + 1  
    else:
        E[i,j] = k
    return E @ A

def skaler_rad(A,k,i):
    "Ganger rad i med k."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

def bytt_rad(A,i,j):
    "Bytter om radene i og j."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = 0
    E[j,j] = 0
    E[i,j] = 1
    E[j,i] = 1
    return E @ A

b)

In [50]:
A = np.array([
    [1, 1, 1, 1, 1],
    [0, 0, -1, 0 , 4],
    [2, 2, 3, 5, 5],
    [0, 3, -6, 1, 7],
    [0, 1, 2, 0, -1]
])

b = np.array([[1], [2], [-1], [3], [1]])

print(f'A =\n{A}\n')
print(f'B =\n{b}\n')

A = 
[[ 1  1  1  1  1]
 [ 0  0 -1  0  4]
 [ 2  2  3  5  5]
 [ 0  3 -6  1  7]
 [ 0  1  2  0 -1]]

B = 
[[ 1]
 [ 2]
 [-1]
 [ 3]
 [ 1]]



c)

In [55]:
A[1, 2], A[2, 4], A[3, 1] = 0, 4, -3

print(f'A =\n{A}')

A =
[[ 1  1  1  1  1]
 [ 0  0  0  0  4]
 [ 2  2  3  5  4]
 [ 0 -3 -6  1  7]
 [ 0  1  2  0 -1]]


d)

In [52]:
M = np.column_stack((A, b))
print(f'M =\n{M}')

M =
[[ 1  1  1  1  1  1]
 [ 0  0  0  0  4  2]
 [ 2  2  3  5  4 -1]
 [ 0 -3 -6  1  7  3]
 [ 0  1  2  0 -1  1]]


e)

In [54]:
M1 = adder_rad(M, -2, 2, 0)
M2 = bytt_rad(M1, 1, 4)
M3 = adder_rad(M2, 3, 3, 1)
M4 = skaler_rad(M3, 1/4, 4)
print(M4)

[[ 1.   1.   1.   1.   1.   1. ]
 [ 0.   1.   2.   0.  -1.   1. ]
 [ 0.   0.   1.   3.   2.  -3. ]
 [ 0.   0.   0.   1.   4.   6. ]
 [ 0.   0.   0.   0.   1.   0.5]]


f)

In [58]:
x5, x4, x3, x2, x1 = M4[4, 5], M4[3, 5] - 4*x5, M4[2, 5] - 3*x4 - 2*x5, M4[1, 5] - 2*x3 + x5, M4[0, 5] - x2 - x3 - x4 -x5
print(f"x1: {x1}\nx2: {x2}\nx3: {x3}\nx4: {x4}\nx5: {x5}")

x1: -21.0
x2: 33.5
x3: -16.0
x4: 4.0
x5: 0.5


g)

In [46]:
ans = np.linalg.solve(A, b)
check = np.allclose(np.dot(A, ans), b)

print(f"The answer is:\nx1: {ans[0]}\nx2: {ans[1]}\nx3: {ans[2]}\nx4: {ans[3]}\nx5: {ans[4]}\n\nAnswer is correct: {check}")

The answer is:
x1: [-21.]
x2: [33.5]
x3: [-16.]
x4: [4.]
x5: [0.5]

Answer is correct: True
